name: Movies CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Installing NPM
      run: npm install
    - name: Running Unit Tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "rbekyarov"
  deploy:  
    runs-on: ubuntu-latest
    needs: build
    steps:      
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.MY_RENDER_API_KEY }}

  ui_tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Installing NPM
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps        
      - name: Running UI Tests
        run: npm run test:ui
